name: fake-08

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  first:
    name: android-libretro
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules : recursive

      - name: Setup NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r21e

      - name: Build
        run: cd platform/libretro/jni && ndk-build

      - name: Rename Artifacts
        run: | 
          cp platform/libretro/libs/arm64-v8a/libfake08.so platform/libretro/libs/libfake08-arm64.so && 
          cp platform/libretro/libs/armeabi-v7a/libfake08.so platform/libretro/libs/libfake08-arm32.so

      - uses: actions/upload-artifact@v2
        with:
          name: Android-Libretro
          path: |
            platform/libretro/libs/libfake08-arm64.so
            platform/libretro/libs/libfake08-arm32.so
  
  second:
    name: MiyooMini-libretro
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules : recursive

      - name: Build
        run: |
          docker run -e ENABLE_COMPATIBILITY_REPORTING -v $GITHUB_WORKSPACE:/build_dir jondbell/union-miyoomini-toolchain /bin/sh -ex /build_dir/.github/workflows/buildMiyooMini-libretro.sh

      - uses: actions/upload-artifact@v2
        with:
          name: MiyooMini-libretro
          path: |
            platform/libretro/fake08_libretro_miyoomini.so

  third:
    name: GCW0-libretro
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules : recursive

      - name: Build
        run: |
          docker run -e ENABLE_COMPATIBILITY_REPORTING -v $GITHUB_WORKSPACE:/build_dir jondbell/gcw0 /bin/sh -ex /build_dir/.github/workflows/buildGcw0-libretro.sh

      - uses: actions/upload-artifact@v2
        with:
          name: GCW0-libretro
          path: |
            platform/libretro/fake08_libretro_gcw0.so